// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Mxp.Core.Business;
using Mxp.Core;
using System.Collections.ObjectModel;

namespace Mxp.iOS
{
	public partial class AllowanceSegmentTableViewController : MXPTableViewController
	{
		public AllowanceSegmentTableViewController (IntPtr handle) : base (handle)
		{
		}

		public AllowanceSegment segment;

		public Collection<DataFieldCell> fields;

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
			this.Title = Labels.GetLoggedUserLabel (Labels.LabelEnum.SegmentDetails);
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);

			this.fields = FieldFactory.WrapFields (this.segment.GetAllowanceFields());

			this.TableView.Source = new SegmentTableViewSource (this.fields, this.ParentViewController);
			this.TableView.ReloadData ();
					
		}
	}

	public class SegmentTableViewSource : UITableViewSource
	{
	
		private Collection<DataFieldCell> fields;

		public UIViewController ViewController;

		public SegmentTableViewSource (Collection<DataFieldCell> fields, UIViewController viewController){
			this.fields = fields;

			this.ViewController = viewController;

		}

		public override nint NumberOfSections (UITableView tableView)
		{
			return 1;
		}

		public override nint RowsInSection (UITableView tableview, nint section)
		{
			return this.fields.Count;
		}

		public override UITableViewCell GetCell (UITableView tableView, NSIndexPath indexPath)
		{
			return FieldFactory.GetCell (tableView, this.fields [indexPath.Row]);
		}

		public void RowSelected (UITableView tableView, NSIndexPath indexPath)
		{
			this.fields [indexPath.Row].FieldSelected (this.ViewController, tableView, tableView.CellAt(indexPath));
		}
	}

}
