// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by coded UI test builder.
//      Version: 14.0.0.0
//
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------

namespace Mxp.UITests.WindowsPhone
{
    using System;
    using System.CodeDom.Compiler;
    using System.Collections.Generic;
    using Microsoft.VisualStudio.TestPlatform.UnitTestFramework;
    using Microsoft.VisualStudio.TestTools.UITest.Extension;
    using Microsoft.VisualStudio.TestTools.UITest.Input;
    using Microsoft.VisualStudio.TestTools.UITesting;
    using Microsoft.VisualStudio.TestTools.UITesting.WindowsRuntimeControls;
    
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public partial class UIMap
    {
        
        #region Properties
        public UIMobileXpenseWindow UIMobileXpenseWindow
        {
            get
            {
                if ((this.mUIMobileXpenseWindow == null))
                {
                    this.mUIMobileXpenseWindow = new UIMobileXpenseWindow();
                }
                return this.mUIMobileXpenseWindow;
            }
        }
        #endregion
        
        #region Fields
        private UIMobileXpenseWindow mUIMobileXpenseWindow;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIMobileXpenseWindow : XamlWindow
    {
        
        public UIMobileXpenseWindow()
        {
            #region Search Criteria
            this.SearchProperties[XamlControl.PropertyNames.Name] = "MobileXpense";
            #endregion
        }
        
        #region Properties
        public UIHubHub UIHubHub
        {
            get
            {
                if ((this.mUIHubHub == null))
                {
                    this.mUIHubHub = new UIHubHub(this);
                }
                return this.mUIHubHub;
            }
        }
        
        public XamlList UIItemsListList
        {
            get
            {
                if ((this.mUIItemsListList == null))
                {
                    this.mUIItemsListList = new XamlList(this);
                    #region Search Criteria
                    this.mUIItemsListList.SearchProperties[XamlList.PropertyNames.AutomationId] = "ItemsList";
                    #endregion
                }
                return this.mUIItemsListList;
            }
        }
        #endregion
        
        #region Fields
        private UIHubHub mUIHubHub;
        
        private XamlList mUIItemsListList;
        #endregion
    }
    
    [GeneratedCode("Coded UITest Builder", "14.0.23107.0")]
    public class UIHubHub : XamlHub
    {
        
        public UIHubHub(XamlControl searchLimitContainer) : 
                base(searchLimitContainer)
        {
            #region Search Criteria
            this.SearchProperties[XamlHub.PropertyNames.AutomationId] = "Hub";
            #endregion
        }
        
        #region Properties
        public XamlEdit UIUsernameEdit
        {
            get
            {
                if ((this.mUIUsernameEdit == null))
                {
                    this.mUIUsernameEdit = new XamlEdit(this);
                    #region Search Criteria
                    this.mUIUsernameEdit.SearchProperties[XamlEdit.PropertyNames.AutomationId] = "Username";
                    #endregion
                }
                return this.mUIUsernameEdit;
            }
        }
        
        public XamlEdit UIPasswordEdit
        {
            get
            {
                if ((this.mUIPasswordEdit == null))
                {
                    this.mUIPasswordEdit = new XamlEdit(this);
                    #region Search Criteria
                    this.mUIPasswordEdit.SearchProperties[XamlEdit.PropertyNames.AutomationId] = "Password";
                    #endregion
                }
                return this.mUIPasswordEdit;
            }
        }
        
        public XamlButton UILoginButton
        {
            get
            {
                if ((this.mUILoginButton == null))
                {
                    this.mUILoginButton = new XamlButton(this);
                    #region Search Criteria
                    this.mUILoginButton.SearchProperties[XamlButton.PropertyNames.AutomationId] = "UserLoginButton";
                    #endregion
                }
                return this.mUILoginButton;
            }
        }
        #endregion
        
        #region Fields
        private XamlEdit mUIUsernameEdit;
        
        private XamlEdit mUIPasswordEdit;
        
        private XamlButton mUILoginButton;
        #endregion
    }
}
