// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Mxp.iOS
{
	public partial class IpadExpenseDetailViewController : MXPViewController
	{
		public IpadExpenseDetailViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
