// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Mxp.Core.Business;
using System.Collections.ObjectModel;

using SDWebImage;
using System.Collections.Generic;

namespace Mxp.iOS
{
	public partial class GalleryViewController : MXPViewController
	{
		public GalleryViewController (IntPtr handle) : base (handle)
		{
		}

		public Receipts Receipts;

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
			this.configureImages ();
		}

		private Collection<UIImageView> Images;

		public void configureImages(){
			this.Images = new Collection<UIImageView> ();

			this.ScrollContent.BackgroundColor = UIColor.White;

			this.ScrollContent.TranslatesAutoresizingMaskIntoConstraints = false;
			this.ScrollContent.SetNeedsLayout ();
			this.ScrollContent.LayoutIfNeeded ();


			var index = 0;
			UIImageView precendenteImageView = null;
			foreach (Receipt receipt in this.Receipts) {
				UIImageView currentImage = new UIImageView ();

				if (receipt.IsDocument) {
					currentImage.Image = UIImage.FromBundle ("DocumentExpenseCell.png");
				} else {
					currentImage.SetImage (new NSUrl (receipt.AttachmentPath));
				}

				currentImage.BackgroundColor = UIColor.Green;
				this.ScrollContent.AddSubview (currentImage);

				NSDictionary dict = NSDictionary.FromObjectsAndKeys (new NSObject[]{ currentImage, precendenteImageView }, new NSObject[]{ new NSString ("currentImage"), new NSString ("precendenteImageView")});

				NSDictionary size = NSDictionary.FromObjectsAndKeys (new NSObject[]{new NSNumber(this.ScrollView.Frame.Size.Width), new NSNumber(this.ScrollView.Frame.Size.Height) }, new NSObject[]{ new NSString ("width"), new NSString ("height")});

				ScrollContent.AddConstraints (NSLayoutConstraint.FromVisualFormat ("V:|-[currentImage(400)]-|",0,size, dict));

				if (precendenteImageView != null) {
					//Configure left part
					ScrollContent.AddConstraints (NSLayoutConstraint.FromVisualFormat ("H:[precendenteImageView]-[currentImage(300)]", 0, size, dict));
				} else {
					ScrollContent.AddConstraints (NSLayoutConstraint.FromVisualFormat ("H:|-[currentImage(300)]", 0, size, dict));
				}

				if (index == this.Receipts.Count -1) {
					//Configure right part
					ScrollContent.AddConstraints (NSLayoutConstraint.FromVisualFormat ("H:[currentImage]-10-|", 0, null, dict));
				}


				this.ScrollContent.SetNeedsLayout ();
				this.ScrollContent.LayoutIfNeeded ();

				index++;
				precendenteImageView = currentImage;
			}

		}


	}
}
