// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Mxp.iOS
{
	public partial class AllowanceDetailsTableViewController : MXPTableViewController
	{
		public AllowanceDetailsTableViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
