// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace MXPiOS
{
	public partial class AttendeeCell : UITableViewCell
	{
		public AttendeeCell (IntPtr handle) : base (handle)
		{
		}
	}
}
