// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Foundation;

namespace MXPiOS
{
	public partial class HCOViewController : UIViewController
	{
		public HCOViewController (IntPtr handle) : base (handle)
		{
		}
	}
}
