// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Mxp.Core.Business;
using Mxp.Core.Utils;
using System.Threading.Tasks;
using Mxp.Core;
using System.ComponentModel;

namespace Mxp.iOS
{
	public partial class ApproveExpensesTableViewController : MXPTableViewController, IReportDetailsSubController
	{
		public Report Report { get; set;}

		private ApprovedExpenseSectionSource source;

		public ApproveExpensesTableViewController () : base () {
			
		}
			
		public void showExpense(ExpenseItem expenseItem) {
			UIViewController nextVC = null;
			if (expenseItem.ParentExpense is Mileage) {
				nextVC = new MileageViewController (expenseItem.ParentExpense as Mileage);
			} else if (expenseItem.ParentExpense is Allowance) {
				nextVC = new AllowanceViewController (expenseItem.ParentExpense as Allowance);
			} else {
				ExpenseDetailViewController vc = UIStoryboard.FromName ("ExpenseDetailsStoryboard", NSBundle.MainBundle).InstantiateInitialViewController () as ExpenseDetailViewController;
				vc.setExpenseItem (expenseItem);
				nextVC = vc;
			}
			this.NavigationController.PushViewController (nextVC, true);
		}

		public override void ViewDidAppear (bool animated) {
			base.ViewDidAppear (animated);

			this.source = new ApprovedExpenseSectionSource (this.Report);
			this.source.cellSelected += (object sender, ExpenseSelectedEventArgs e) => {
				if(e.model is Expense) {
					this.showExpense(((Expense)e.model).ExpenseItems[0]);
				} else if(e.model is ExpenseItem) {
					this.showExpense(e.model as ExpenseItem);
				}
			};
			this.TableView.Source = this.source;

			this.Report.Expenses.DeploySplits ();
			this.TableView.ReloadData ();
		}
	}
}