// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Mxp.Core.Business;
using System.Threading.Tasks;
using Mxp.Core.Services;

namespace Mxp.iOS
{
	public partial class ReportReceiptsCollectionViewController : UICollectionViewController, IReportDetailsSubController
	{
		public Report Report { get; set; }

		private ReceiptsFlowLayout flowLayout;

		public ReportReceiptsCollectionViewController (IntPtr handle) : base (handle) {
			
		}

		public override void ViewDidLoad () {
			base.ViewDidLoad ();

			this.CollectionView.RegisterNibForCell (UINib.FromName ("ReceiptCell", null), new NSString("ReceiptCell"));
			this.CollectionView.RegisterNibForCell (UINib.FromName ("AddReceiptCell", null), new NSString("AddReceiptCell"));

			flowLayout =  new ReceiptsFlowLayout ();
			flowLayout.Receipts = this.Report.Receipts;
			flowLayout.viewController = this;
			flowLayout.collectionView = this.CollectionView;

			this.CollectionView.Source = new ReceiptsCollectionSource (this.Report.Receipts);
		}

		public override void ViewWillAppear (bool animated) {
			base.ViewWillAppear (animated);

			flowLayout.SelectImage += FlowLayout_SelectImage;

			this.CollectionView.Delegate = flowLayout;

			this.CollectionView.ReloadData ();
		}

		public override void ViewWillDisappear (bool animated) {
			flowLayout.SelectImage -= FlowLayout_SelectImage;

			base.ViewWillDisappear (animated);
		}

		async void ProcessImage (string base64) {
			if (!this.Report.IsNew) {
				LoadingView.showMessage (Labels.GetLoggedUserLabel (Labels.LabelEnum.Uploading));
			}

			try {
				await this.Report.Receipts.AddReceipt (base64);
			} catch (Exception e) {
				MainNavigationController.Instance.showError (e);
				return;
			} finally {
				LoadingView.hideMessage ();
			}

			this.CollectionView.ReloadData ();
		}

		void FlowLayout_SelectImage (object sender, SelectImageEventArgs e) {
			this.ProcessImage (e.base64);	
		}
	}
}