// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;
using Mxp.Core.Business;

namespace Mxp.iOS
{
	public partial class IPadReportSplitViewController : MXPSplitViewController
	{
		public IPadReportSplitViewController (IntPtr handle) : base (handle) {
			
		}

		public override void ViewDidLoad () {
			base.ViewDidLoad ();

			((ReportsViewController)this.listViewController).cellSelected += (sender, e) => {
				this.showReport(e.Report);
			};
		}

		public void showReport(Report report) {
			if (report == null) {
				this.ShouldShowDetailViewController (this.Storyboard.InstantiateViewController ("EmptyReport"), this);
				return;
			}

			UIStoryboard storyBoard = UIStoryboard.FromName ("ReportDetails", null);	
			ReportDetailsViewController reportDetailsViewController = storyBoard.InstantiateInitialViewController () as ReportDetailsViewController;
			reportDetailsViewController.Report = report;

			if (report.IsNew) {
				var nvc = new UINavigationController (reportDetailsViewController);
				nvc.ModalPresentationStyle = UIModalPresentationStyle.PageSheet;
				this.PresentViewController (nvc, true, null);
				return;
			}

			this.ShouldShowDetailViewController (reportDetailsViewController, this);
		}
	}
}