// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace sc
{
	public partial class LogViewController : UIViewController
	{
		public LogViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewDidLoad ()
		{
			base.ViewDidLoad ();
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
			this.TextArea.Editable = false;

			this.TextArea.Text = this.log;
		}


		string log = "";

		public void addLog(string log) {
			this.log += "\n" + log;
//			TextArea.Text = this.log;
		}

	}
}
