// This file has been autogenerated from a class added in the UI designer.

using System;

using Foundation;
using UIKit;

namespace Mxp.iOS
{
	public partial class ForgotPasswordViewController : MXPViewController
	{
		public ForgotPasswordViewController (IntPtr handle) : base (handle)
		{
		}

		public override void ViewWillAppear (bool animated)
		{
			base.ViewWillAppear (animated);
			this.FormContainer.Layer.CornerRadius = 5;
			this.NavigationController.SetNavigationBarHidden (false, true);

			this.SendButton.Layer.CornerRadius = 4;
			this.SendButton.Layer.BorderWidth = 1;
			this.SendButton.Layer.BorderColor =  UIColor.FromRGB (0, 134, 158).CGColor;
		}
	}
}
